module.exports = {
	"mount_point": "#app",
	"proxy_url": "http://moodle.local.isae.fr/mod/naas/proxy.php",
	"labels": {
            "search_here" : "search_here",
            "search" : "search",
            "click_to_modify" : "click_to_modify",
            "clear_filters" : "clear_filters",
            "no_nugget" : "no_nugget",
            "see_nugget_details" : "see_nugget_details",
            "back_to_course" : "back_to_course",
            "preview_button" : "preview_button",
            "details_button" : "details_button",
            "metadata" : {
                "preview" : "preview",
                "details" : "details",
                "resume" : "resume",
                "in_brief" : "in_brief",
                "about_author" : "about_author",
                "learning_outcomes" : "learning_outcomes",
                "prerequisites" : "prerequisites",
                "references" : "references",
                "field_of_study" : "field_of_study",
                "language" : "language",
                "duration" : "duration",
                "level" : "level",
                "structure_id" : "structure_id",
                "advanced" : "advanced",
                "intermediate" : "intermediate",
                "beginner" : "beginner",
                "tags" : "tags",
                "en" : "en",
                "english" : "english",
                "fr" : "fr",
                "french" : "french",
            }
	},
    "nugget_id": ""
}