module.exports = {
  mount_point: "#app",
  component: "NuggetInfoWidget",
  //"component": "NuggetSearchWidget",
  proxy_url: "http://moodle.local.isae.fr/mod/naas/proxy.php",
  labels: {
    search_here: "search_here",
    search: "search",
    click_to_modify: "Click to modify",
    clear_filters: "Clear filters",
    no_nugget: "no_nugget",
    preview_button: "Preview",
    details_button: "Details",
    see_nugget_details: "Details",
    loading: "Chargement...",
    metadata: {
      learning_outcomes: "Learning outcomes",
      prerequisites: "Prerequisites",
      references: "References",
      field_of_study: "Field of study",
      about_author: "About the author",
      language: "Language",
      duration: "duration",
      level: "Level",
      structure_id: "structure_id",
      advanced: "Advanced",
      intermediate: "Intermediate",
      beginner: "Beginner",
      tags: "Tags",
      producers: "Producers",
      authors: "Authors",
      type: "Type",
      lesson: "Lesson",
      tutorial: "Tutorial",
      demo: "Demo",
      related_domains: "Fields of study",
    },
  },
  nugget_id: "",
  //nugget_id: "338b4335-204f-4166-8e64-581425de5b1e",
};
